# unadf

LIBDIR=../Lib
LIBNAME=libadf.a

DEPEND=makedepend

CFLAGS=-I$(LIBDIR) -O2 -Wall -g
LDFLAGS=-L$(LIBDIR) -ladf

EXES= unadf


all: $(EXES)

lib:
	cd $(LIBDIR) && $(MAKE)

unadf: lib unadf.o
	$(CC) $(CFLAGS) -o $@ unadf.o $(LDFLAGS)

clean:
	rm *.o $(EXES) core newdev

depend:
	$(DEPEND) -v -- $(CFLAGS) --  *.[ch]


# DO NOT DELETE THIS LINE -- make depend depends on it.

