# ADFLib Makefile for Unix platforms
# tested on Solaris 2.5 and Linux 2.0.34 (RedHat 5.1) 


# real devices routines location
NATIV_DIR = ./Generic

VER=0.7.1
LIBS=libadf.a
SHAREDLIB=libadf.so

AR=ar rc
RANLIB=ranlib
TAR=tar

DEFINES= 

CFLAGS=$(DEFINES) -I${NATIV_DIR} -I.. -I. -Wall -O2

CC=gcc 
DEPEND=makedepend

LDFLAGS=-L. -ladf
LDSHARED=$(CC)

OBJS=	 adf_hd.o adf_disk.o adf_raw.o adf_bitm.o adf_dump.o\
        adf_util.o adf_env.o adf_nativ.o adf_dir.o adf_file.o adf_cache.o \
        adf_link.o

libadf.a: $(OBJS)
	$(AR) $@ $(OBJS)
	-@ ($(RANLIB) $@ || true) >/dev/null 2>&1

$(SHAREDLIB).$(VER): $(OBJS)
	$(LDSHARED) -o $@ $(OBJS)
	rm -f $(SHAREDLIB) $(SHAREDLIB).1
	ln -s $@ $(SHAREDLIB)
	ln -s $@ $(SHAREDLIB).1


# to define LITT_ENDIAN on little endian machines (intel)
# checks for sizeof(long)=4, sizeof(short)=2, sizeof(int)=4
defendian.h: myconf 
	myconf

adf_nativ.o: ${NATIV_DIR}/adf_nativ.c ${NATIV_DIR}/adf_nativ.h
	$(CC) ${CFLAGS} -c ${NATIV_DIR}/adf_nativ.c

clean:
	@rm $(OBJS)  $(EXE) defendian.h $(LIBS) $(SHAREDLIB)

src:
	@rm adflib.zip
	@zip -9r adflib.zip *.h *.c Makefile myconf Docs Linux Win32 Refs runtest

depend: defendian.h
	$(DEPEND) -v -- $(CFLAGS) --  *.[ch]


# DO NOT DELETE THIS LINE -- make depend depends on it.

adf_bitm.o: /usr/include/stdlib.h
# /usr/include/stdlib.h includes:
#	features.h
#	stddef.h
#	sys/types.h
#	alloca.h
adf_bitm.o: /usr/include/features.h
# /usr/include/features.h includes:
#	sys/cdefs.h
#	gnu/stubs.h
adf_bitm.o: /usr/include/sys/cdefs.h
# /usr/include/sys/cdefs.h includes:
#	features.h
adf_bitm.o: /usr/include/gnu/stubs.h
adf_bitm.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_bitm.o: /usr/include/sys/types.h
# /usr/include/sys/types.h includes:
#	features.h
#	gnu/types.h
#	time.h
#	stddef.h
#	endian.h
#	sys/select.h
adf_bitm.o: /usr/include/gnu/types.h
# /usr/include/gnu/types.h includes:
#	features.h
adf_bitm.o: /usr/include/time.h
# /usr/include/time.h includes:
#	gnu/types.h
adf_bitm.o: /usr/include/endian.h
# /usr/include/endian.h includes:
#	features.h
#	bytesex.h
adf_bitm.o: /usr/include/bytesex.h /usr/include/sys/select.h
# /usr/include/sys/select.h includes:
#	features.h
#	gnu/types.h
#	selectbits.h
#	time.h
adf_bitm.o: /usr/include/selectbits.h /usr/include/alloca.h
# /usr/include/alloca.h includes:
#	features.h
#	stddef.h
adf_bitm.o: /usr/include/string.h
# /usr/include/string.h includes:
#	features.h
#	stddef.h
adf_bitm.o: adf_raw.h
# adf_raw.h includes:
#	defendian.h
#	adf_str.h
adf_bitm.o: defendian.h adf_str.h
# adf_str.h includes:
#	stdio.h
#	adf_defs.h
#	adf_blk.h
#	adf_err.h
adf_bitm.o: /usr/include/stdio.h
# /usr/include/stdio.h includes:
#	libio.h
#	stdio_lim.h
adf_bitm.o: /usr/include/libio.h
# /usr/include/libio.h includes:
#	features.h
#	_G_config.h
#	stdarg.h
adf_bitm.o: /usr/include/_G_config.h
# /usr/include/_G_config.h includes:
#	gnu/types.h
#	stddef.h
adf_bitm.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_bitm.o: /usr/include/stdio_lim.h adf_defs.h adf_blk.h adf_err.h
adf_bitm.o: adf_bitm.h
# adf_bitm.h includes:
#	adf_str.h
adf_bitm.o: adf_disk.h
# adf_disk.h includes:
#	prefix.h
#	adf_str.h
#	adf_defs.h
adf_bitm.o: prefix.h adf_util.h
# adf_util.h includes:
#	prefix.h
#	adf_str.h
adf_bitm.o: adf_str.h /usr/include/stdio.h /usr/include/libio.h
adf_bitm.o: /usr/include/features.h /usr/include/sys/cdefs.h
adf_bitm.o: /usr/include/gnu/stubs.h /usr/include/_G_config.h
adf_bitm.o: /usr/include/gnu/types.h
adf_bitm.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_bitm.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_bitm.o: /usr/include/stdio_lim.h adf_defs.h adf_blk.h adf_err.h
adf_cache.o: /usr/include/stdlib.h /usr/include/features.h
adf_cache.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
adf_cache.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_cache.o: /usr/include/sys/types.h /usr/include/gnu/types.h
adf_cache.o: /usr/include/time.h /usr/include/endian.h /usr/include/bytesex.h
adf_cache.o: /usr/include/sys/select.h /usr/include/selectbits.h
adf_cache.o: /usr/include/alloca.h /usr/include/string.h adf_defs.h adf_str.h
adf_cache.o: /usr/include/stdio.h /usr/include/libio.h
adf_cache.o: /usr/include/_G_config.h
adf_cache.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_cache.o: /usr/include/stdio_lim.h adf_blk.h adf_err.h defendian.h
adf_cache.o: adf_cache.h
# adf_cache.h includes:
#	adf_str.h
adf_cache.o: adf_raw.h adf_disk.h prefix.h adf_bitm.h adf_util.h adf_dir.h
# adf_dir.h includes:
#	adf_str.h
#	adf_err.h
#	adf_defs.h
#	prefix.h
adf_cache.o: adf_str.h /usr/include/stdio.h /usr/include/libio.h
adf_cache.o: /usr/include/features.h /usr/include/sys/cdefs.h
adf_cache.o: /usr/include/gnu/stubs.h /usr/include/_G_config.h
adf_cache.o: /usr/include/gnu/types.h
adf_cache.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_cache.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_cache.o: /usr/include/stdio_lim.h adf_defs.h adf_blk.h adf_err.h
adf_dir.o: /usr/include/stdlib.h /usr/include/features.h
adf_dir.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
adf_dir.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_dir.o: /usr/include/sys/types.h /usr/include/gnu/types.h
adf_dir.o: /usr/include/time.h /usr/include/endian.h /usr/include/bytesex.h
adf_dir.o: /usr/include/sys/select.h /usr/include/selectbits.h
adf_dir.o: /usr/include/alloca.h /usr/include/string.h /usr/include/ctype.h
# /usr/include/ctype.h includes:
#	features.h
#	endian.h
adf_dir.o: adf_dir.h adf_str.h /usr/include/stdio.h /usr/include/libio.h
adf_dir.o: /usr/include/_G_config.h
adf_dir.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_dir.o: /usr/include/stdio_lim.h adf_defs.h adf_blk.h adf_err.h prefix.h
adf_dir.o: adf_util.h defendian.h adf_raw.h adf_disk.h adf_bitm.h adf_file.h
# adf_file.h includes:
#	prefix.h
#	adf_str.h
adf_dir.o: adf_cache.h
adf_dir.o: adf_str.h /usr/include/stdio.h /usr/include/libio.h
adf_dir.o: /usr/include/features.h /usr/include/sys/cdefs.h
adf_dir.o: /usr/include/gnu/stubs.h /usr/include/_G_config.h
adf_dir.o: /usr/include/gnu/types.h
adf_dir.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_dir.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_dir.o: /usr/include/stdio_lim.h adf_defs.h adf_blk.h adf_err.h prefix.h
adf_disk.o: /usr/include/limits.h
# /usr/include/limits.h includes:
#	features.h
#	posix1_lim.h
#	posix2_lim.h
adf_disk.o: /usr/include/features.h /usr/include/sys/cdefs.h
adf_disk.o: /usr/include/gnu/stubs.h /usr/include/posix1_lim.h
# /usr/include/posix1_lim.h includes:
#	local_lim.h
adf_disk.o: /usr/include/local_lim.h
# /usr/include/local_lim.h includes:
#	linux/limits.h
adf_disk.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
adf_disk.o: /usr/include/stdlib.h
adf_disk.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_disk.o: /usr/include/sys/types.h /usr/include/gnu/types.h
adf_disk.o: /usr/include/time.h /usr/include/endian.h /usr/include/bytesex.h
adf_disk.o: /usr/include/sys/select.h /usr/include/selectbits.h
adf_disk.o: /usr/include/alloca.h /usr/include/string.h adf_str.h
adf_disk.o: /usr/include/stdio.h /usr/include/libio.h
adf_disk.o: /usr/include/_G_config.h
adf_disk.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_disk.o: /usr/include/stdio_lim.h adf_defs.h adf_blk.h adf_err.h
adf_disk.o: adf_disk.h prefix.h adf_raw.h defendian.h adf_hd.h
# adf_hd.h includes:
#	prefix.h
#	adf_str.h
#	hd_blk.h
#	defendian.h
#	adf_err.h
adf_disk.o: hd_blk.h
# hd_blk.h includes:
#	adf_str.h
adf_disk.o: adf_bitm.h adf_util.h ./Generic/adf_nativ.h
# ./Generic/adf_nativ.h includes:
#	stdio.h
#	adf_str.h
adf_disk.o: adf_dump.h adf_cache.h
adf_disk.o: prefix.h adf_str.h /usr/include/stdio.h /usr/include/libio.h
adf_disk.o: /usr/include/features.h /usr/include/sys/cdefs.h
adf_disk.o: /usr/include/gnu/stubs.h /usr/include/_G_config.h
adf_disk.o: /usr/include/gnu/types.h
adf_disk.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_disk.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_disk.o: /usr/include/stdio_lim.h adf_defs.h adf_blk.h adf_err.h
adf_dump.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/features.h
adf_dump.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
adf_dump.o: /usr/include/_G_config.h /usr/include/gnu/types.h
adf_dump.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_dump.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_dump.o: /usr/include/stdio_lim.h /usr/include/stdlib.h
adf_dump.o: /usr/include/sys/types.h /usr/include/time.h
adf_dump.o: /usr/include/endian.h /usr/include/bytesex.h
adf_dump.o: /usr/include/sys/select.h /usr/include/selectbits.h
adf_dump.o: /usr/include/alloca.h adf_defs.h adf_str.h adf_blk.h adf_err.h
adf_dump.o: ./Generic/adf_nativ.h
adf_env.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/features.h
adf_env.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
adf_env.o: /usr/include/_G_config.h /usr/include/gnu/types.h
adf_env.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_env.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_env.o: /usr/include/stdio_lim.h /usr/include/stdlib.h
adf_env.o: /usr/include/sys/types.h /usr/include/time.h /usr/include/endian.h
adf_env.o: /usr/include/bytesex.h /usr/include/sys/select.h
adf_env.o: /usr/include/selectbits.h /usr/include/alloca.h adf_defs.h
adf_env.o: adf_str.h adf_blk.h adf_err.h ./Generic/adf_nativ.h adf_env.h
# adf_env.h includes:
#	prefix.h
adf_env.o: prefix.h
adf_env.o: prefix.h
adf_file.o: /usr/include/stdlib.h /usr/include/features.h
adf_file.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
adf_file.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_file.o: /usr/include/sys/types.h /usr/include/gnu/types.h
adf_file.o: /usr/include/time.h /usr/include/endian.h /usr/include/bytesex.h
adf_file.o: /usr/include/sys/select.h /usr/include/selectbits.h
adf_file.o: /usr/include/alloca.h /usr/include/string.h adf_util.h prefix.h
adf_file.o: adf_str.h /usr/include/stdio.h /usr/include/libio.h
adf_file.o: /usr/include/_G_config.h
adf_file.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_file.o: /usr/include/stdio_lim.h adf_defs.h adf_blk.h adf_err.h
adf_file.o: adf_file.h defendian.h adf_raw.h adf_disk.h adf_dir.h adf_bitm.h
adf_file.o: adf_cache.h
adf_file.o: prefix.h adf_str.h /usr/include/stdio.h /usr/include/libio.h
adf_file.o: /usr/include/features.h /usr/include/sys/cdefs.h
adf_file.o: /usr/include/gnu/stubs.h /usr/include/_G_config.h
adf_file.o: /usr/include/gnu/types.h
adf_file.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_file.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_file.o: /usr/include/stdio_lim.h adf_defs.h adf_blk.h adf_err.h
adf_hd.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/features.h
adf_hd.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
adf_hd.o: /usr/include/_G_config.h /usr/include/gnu/types.h
adf_hd.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_hd.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_hd.o: /usr/include/stdio_lim.h /usr/include/stdlib.h
adf_hd.o: /usr/include/sys/types.h /usr/include/time.h /usr/include/endian.h
adf_hd.o: /usr/include/bytesex.h /usr/include/sys/select.h
adf_hd.o: /usr/include/selectbits.h /usr/include/alloca.h
adf_hd.o: /usr/include/string.h adf_str.h adf_defs.h adf_blk.h adf_err.h
adf_hd.o: hd_blk.h adf_raw.h defendian.h adf_hd.h prefix.h adf_util.h
adf_hd.o: adf_disk.h ./Generic/adf_nativ.h adf_dump.h
adf_hd.o: prefix.h adf_str.h /usr/include/stdio.h /usr/include/libio.h
adf_hd.o: /usr/include/features.h /usr/include/sys/cdefs.h
adf_hd.o: /usr/include/gnu/stubs.h /usr/include/_G_config.h
adf_hd.o: /usr/include/gnu/types.h
adf_hd.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_hd.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_hd.o: /usr/include/stdio_lim.h adf_defs.h adf_blk.h adf_err.h hd_blk.h
adf_hd.o: defendian.h
adf_raw.o: /usr/include/limits.h /usr/include/features.h
adf_raw.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
adf_raw.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
adf_raw.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
adf_raw.o: /usr/include/stdlib.h
adf_raw.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_raw.o: /usr/include/sys/types.h /usr/include/gnu/types.h
adf_raw.o: /usr/include/time.h /usr/include/endian.h /usr/include/bytesex.h
adf_raw.o: /usr/include/sys/select.h /usr/include/selectbits.h
adf_raw.o: /usr/include/alloca.h /usr/include/string.h adf_str.h
adf_raw.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h
adf_raw.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_raw.o: /usr/include/stdio_lim.h adf_defs.h adf_blk.h adf_err.h adf_raw.h
adf_raw.o: defendian.h adf_disk.h prefix.h adf_util.h
adf_raw.o: defendian.h adf_str.h /usr/include/stdio.h /usr/include/libio.h
adf_raw.o: /usr/include/features.h /usr/include/sys/cdefs.h
adf_raw.o: /usr/include/gnu/stubs.h /usr/include/_G_config.h
adf_raw.o: /usr/include/gnu/types.h
adf_raw.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_raw.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_raw.o: /usr/include/stdio_lim.h adf_defs.h adf_blk.h adf_err.h
adf_str.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/features.h
adf_str.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
adf_str.o: /usr/include/_G_config.h /usr/include/gnu/types.h
adf_str.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_str.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_str.o: /usr/include/stdio_lim.h adf_defs.h adf_blk.h adf_err.h
adf_util.o: /usr/include/stdlib.h /usr/include/features.h
adf_util.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
adf_util.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_util.o: /usr/include/sys/types.h /usr/include/gnu/types.h
adf_util.o: /usr/include/time.h /usr/include/endian.h /usr/include/bytesex.h
adf_util.o: /usr/include/sys/select.h /usr/include/selectbits.h
adf_util.o: /usr/include/alloca.h adf_util.h prefix.h adf_str.h
adf_util.o: /usr/include/stdio.h /usr/include/libio.h
adf_util.o: /usr/include/_G_config.h
adf_util.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_util.o: /usr/include/stdio_lim.h adf_defs.h adf_blk.h adf_err.h
adf_util.o: prefix.h adf_str.h /usr/include/stdio.h /usr/include/libio.h
adf_util.o: /usr/include/features.h /usr/include/sys/cdefs.h
adf_util.o: /usr/include/gnu/stubs.h /usr/include/_G_config.h
adf_util.o: /usr/include/gnu/types.h
adf_util.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
adf_util.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
adf_util.o: /usr/include/stdio_lim.h adf_defs.h adf_blk.h adf_err.h
hd_blk.o: adf_str.h /usr/include/stdio.h /usr/include/libio.h
hd_blk.o: /usr/include/features.h /usr/include/sys/cdefs.h
hd_blk.o: /usr/include/gnu/stubs.h /usr/include/_G_config.h
hd_blk.o: /usr/include/gnu/types.h
hd_blk.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
hd_blk.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
hd_blk.o: /usr/include/stdio_lim.h adf_defs.h adf_blk.h adf_err.h
