name: Windows Build & Test

on:
  push:
    branches: [ main ]
    tags: ["v*"]


jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Set Version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "PROJECT_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "PROJECT_VERSION=dev-${{ github.run_number }}" >> $GITHUB_ENV
          fi

      - name: Get Tag Annotation
        if: startsWith(github.ref, 'refs/tags/')
        id: tag_message
        run: |
          TAG_MESSAGE=$(git for-each-ref refs/tags/${{ github.ref_name }} --format='%(contents)')
          echo "::set-output name=message::$TAG_MESSAGE"

      - name: Configure CMake (Release)
        run: cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Run Tests
        run: ctest --test-dir build --verbose

      - name: Zip EXE
        run: |
          powershell Compress-Archive -Path build\Release\adf_make.exe -DestinationPath build\Release\adf_make_win32_${{ env.PROJECT_VERSION }}.zip

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "adf_make_win32_${{ env.PROJECT_VERSION }}"
          path: "build/Release/adf_make_win32_${{ env.PROJECT_VERSION }}.zip"

      - name: Create Release
       # if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: ${{ steps.tag_message.outputs.message }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZIP to Release
      #  if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: build/Release/adf_make_${{ env.PROJECT_VERSION }}.zip
          asset_name: adf_make_${{ env.PROJECT_VERSION }}.zip
          asset_content_type: application/zip