name: Windows Build & Test

on:
  push:
    branches: [ main ]
    tags: ["v*"]

env:
  MAJOR_MINOR_VERSION: "0.0"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Set Version
        run: echo "PROJECT_VERSION=${{ env.MAJOR_MINOR_VERSION }}.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Configure CMake (Release)
        run: cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Run Tests
        run: ctest --test-dir build --verbose

      - name: Zip EXE
        run: |
          powershell Compress-Archive -Path build\Release\adf_make.exe -DestinationPath build\Release\adf_make_win32_${{ env.PROJECT_VERSION }}.zip

      - name: Create Release
       # if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## Changes
            Add your release notes here.

      - name: Upload ZIP to Release
      #  if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: build/Release/adf_make_${{ env.PROJECT_VERSION }}.zip
          asset_name: adf_make_${{ env.PROJECT_VERSION }}.zip
          asset_content_type: application/zip